import type { Ticket, SupportStaff } from "../types/ticket";

export const adminStaff: SupportStaff[] = [
  {
    id: "staff-1",
    name: "Sarah Chen",
    email: "sarah.chen@company.com",
    role: "Senior IT Support",
    avatar: "SC",
    active: true,
  },
  {
    id: "staff-2",
    name: "Marcus Johnson",
    email: "marcus.j@company.com",
    role: "IT Support Specialist",
    avatar: "MJ",
    active: true,
  },
  {
    id: "staff-3",
    name: "Emily Rodriguez",
    email: "emily.r@company.com",
    role: "Network Administrator",
    avatar: "ER",
    active: true,
  },
  {
    id: "staff-4",
    name: "David Kim",
    email: "david.kim@company.com",
    role: "Hardware Support",
    avatar: "DK",
    active: true,
  },
];

export const adminTickets: Ticket[] = [
  {
    id: "TK-1001",
    subject: "VPN connection dropping intermittently",
    category: "Network",
    priority: "high",
    status: "open",
    createdAt: "2026-08-12T09:30:00Z",
    updatedAt: "2026-08-13T08:15:00Z",
    description: "VPN drops every 15-20 minutes when working remotely.",
    submittedBy: "user@company.com",
    assignedTo: "staff-3",
  },
  {
    id: "TK-1002",
    subject: "Request for Adobe Creative Cloud license",
    category: "Software",
    priority: "medium",
    status: "in_progress",
    createdAt: "2026-08-10T14:20:00Z",
    updatedAt: "2026-08-12T11:00:00Z",
    description: "Need Adobe CC for the design team.",
    submittedBy: "design.team@company.com",
    assignedTo: "staff-1",
  },
  {
    id: "TK-1003",
    subject: "Laptop screen flickering after update",
    category: "Hardware",
    priority: "critical",
    status: "open",
    createdAt: "2026-08-13T07:45:00Z",
    updatedAt: "2026-08-13T07:45:00Z",
    description: "Screen flickers on boot after Windows update.",
    submittedBy: "user@company.com",
    assignedTo: "staff-4",
  },
  {
    id: "TK-1004",
    subject: "Email sync delay on mobile",
    category: "Email",
    priority: "low",
    status: "resolved",
    createdAt: "2026-08-01T10:00:00Z",
    updatedAt: "2026-08-05T16:30:00Z",
    description: "Mobile mail app delays new emails by ~10 minutes.",
    submittedBy: "user@company.com",
    assignedTo: "staff-2",
  },
  {
    id: "TK-1005",
    subject: "Printer not responding on 3rd floor",
    category: "Hardware",
    priority: "medium",
    status: "closed",
    createdAt: "2026-07-28T08:00:00Z",
    updatedAt: "2026-08-02T09:00:00Z",
    description: "Printer shows offline status.",
    submittedBy: "floor.3@company.com",
    assignedTo: "staff-4",
  },
  {
    id: "TK-1006",
    subject: "New employee onboarding - equipment request",
    category: "Hardware",
    priority: "high",
    status: "open",
    createdAt: "2026-08-13T10:00:00Z",
    updatedAt: "2026-08-13T10:00:00Z",
    description:
      "Need laptop, monitor, and keyboard for new hire starting next Monday.",
    submittedBy: "hr@company.com",
    assignedTo: "staff-1",
  },
  {
    id: "TK-1007",
    subject: "Shared drive access permission error",
    category: "Access",
    priority: "medium",
    status: "in_progress",
    createdAt: "2026-08-11T13:20:00Z",
    updatedAt: "2026-08-12T09:00:00Z",
    description: "Unable to access the Marketing shared drive folder.",
    submittedBy: "marketing@company.com",
    assignedTo: "staff-2",
  },
  {
    id: "TK-1008",
    subject: "Firewall blocking internal application",
    category: "Network",
    priority: "critical",
    status: "open",
    createdAt: "2026-08-13T11:30:00Z",
    updatedAt: "2026-08-13T11:30:00Z",
    description:
      "New firewall rules are blocking the internal inventory system.",
    submittedBy: "warehouse@company.com",
    assignedTo: "staff-3",
  },
];
